### ISSUE TITLE
How to calculate transition score for each cell?

### ISSUE THREAD

**Issue by petrsh** [morris-lab/Capybara#1]
Hi,
as I mentioned in our conversation on Twitter I can't figure out how to calculate transition score for each cell. I managed to construct a reference and performed a classification for the new dataset. Then I filtered cells with multiple identities using multi.id.curate.qp and I used the first list returned by this function as the input to the transition.score function (please see below the screenshot). This function returned df with entropy for each cell type (second screenshot below). Basically, I was following the tutorial except that I skipped the first step.
![Screenshot 2020-08-08 at 11 55 43](https://user-images.githubusercontent.com/55283841/89707450-42e2a100-d96e-11ea-838c-d94e0edb8d1c.png)
![Screenshot 2020-08-08 at 11 59 53](https://user-images.githubusercontent.com/55283841/89707487-b684ae00-d96e-11ea-95b7-b6a6b6c84e52.png)

**Comment by KaetheKong** [comment]
Hi Petr,

First of all, thank you for using Capybara!

I think this is actually the correct result! It is kind of confusing what the transition scores are measuring and I apologize for the confusion in the tutorial! The transition score (which is the entropy column here, sorry for the confusion!) is actually a measurement for **cell types** instead of individual cells using the multiple identity cells. Considering these cells are in transition, each cell type has various numbers/degrees of connections from these cells, which is what a transition score is measuring. And we consider the cells with discrete identity of such cell type would take the same transition score of the cell type. For instance, if cell type 1 has a score of 3, then all cells identified uniquely as cell type 1 will have the same score. And using this metric, we will be able to tell if there is a more likely state that the cells like to transition through. The transition scores for multiple identity cells are still under development, which we hope to have some updates on this in the future!

Hope this helps!
Let us know if you have more questions!

Best,
Wenjun

**Comment by petrsh** [comment]
Hi Wenjun,

thanks for your reply. Don't apologize, I should have read the method section of your manuscript more carefully before asking this question as everything is very nicely explained there. I'm looking forward to the updates

Best,
Petr
