### ISSUE TITLE
Having trouble with Analysis of Cells with Multiple Identities on the tutorial and missing features.tsv?

### ISSUE THREAD

**Issue by mattli7** [morris-lab/Capybara#13]
Hello,

I am having trouble running the Capybara tutorial and specifically in the “Analysis of Cells with Multiple Identities” in step 2 which is “Preprocessing of the data with Seurat”. I was able to download the file using the code given in step 1, which is: download.file("https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE133452&format=file&file=GSE133452%5Fm1%5F1%5F2%5F3%5F7%5F14P%5Fpaper%2Ecsv%2Egz", "./cardiomyocyte_reprogramming_m1_14p.csv.gz").

However, I run into problems when I run the codes below:
# Read in the file path for all features and genes
feature.file.path <- system.file("extdata", "features.tsv", package = "Capybara")
and 
feature.df <- read.table(feature.file.path, header = F, row.names = 1, stringsAsFactors = F).
Running the code above would give me an error of: 
Error in read.table(feature.file.path, header = F, row.names = 1, stringsAsFactors = F) : 
  no lines available in input.
I then checked feature.file.path to see if there is anything in there and it gave me the output of > feature.file.path
[1] ""
I was just wondering if this was a problem on my end or a problem on your end where the file that I downloaded did not contain a file called “features.tsv”. I cannot find a filed name “features.tsv” on my computer after downloading the gz and unzipping it. Please let me know of any possible solutions to this problem.

Thank you.

**Comment by KaetheKong** [comment]
Hello Matthew,

First of all, thanks for using Capybara! And truly apologize for the delay!

I just checked that I have mistakenly put the features.tsv file under the examples folder instead of as a part of the package. Please download it here - https://github.com/morris-lab/Capybara/tree/master/examples. In this folder, you should be able to find the features.tsv file. Also, I have moved a copy of the file into the extdata. Please try reinstall and see if the code can find it!

Let us know!
Wenjun
